# Generated by Django 2.2.6 on 2019-10-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeansModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=128, unique=True)),
                ('means', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
